// Code generated by "stringer -type=StatusCode -trimprefix Status ./pkg/errs/code.go"; DO NOT EDIT.

package errs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusOK-0]
	_ = x[StatusUnknown-1]
	_ = x[StatusBadRequest-400]
	_ = x[StatusUnauthorized-401]
	_ = x[StatusPaymentRequired-402]
	_ = x[StatusForbidden-403]
	_ = x[StatusNotFound-404]
	_ = x[StatusMethodNotAllowed-405]
	_ = x[StatusNotAcceptable-406]
	_ = x[StatusProxyAuthRequired-407]
	_ = x[StatusRequestTimeout-408]
	_ = x[StatusConflict-409]
	_ = x[StatusGone-410]
	_ = x[StatusLengthRequired-411]
	_ = x[StatusPreconditionFailed-412]
	_ = x[StatusRequestEntityTooLarge-413]
	_ = x[StatusRequestURITooLong-414]
	_ = x[StatusUnsupportedMediaType-415]
	_ = x[StatusRequestedRangeNotSatisfiable-416]
	_ = x[StatusExpectationFailed-417]
	_ = x[StatusTeapot-418]
	_ = x[StatusMisdirectedRequest-421]
	_ = x[StatusUnprocessableEntity-422]
	_ = x[StatusLocked-423]
	_ = x[StatusFailedDependency-424]
	_ = x[StatusTooEarly-425]
	_ = x[StatusUpgradeRequired-426]
	_ = x[StatusPreconditionRequired-428]
	_ = x[StatusTooManyRequests-429]
	_ = x[StatusRequestHeaderFieldsTooLarge-431]
	_ = x[StatusUnavailableForLegalReasons-451]
	_ = x[StatusInternalServerError-500]
	_ = x[StatusServerMaintain-600]
	_ = x[StatusJSONUnmarshalError-601]
	_ = x[StatusNotEnoughResource-603]
	_ = x[StatusInstanceNotFound-604]
	_ = x[StatusDuplicated-605]
	_ = x[StatusTransactionAbort-606]
	_ = x[StatusRequestCanceled-607]
	_ = x[StatusOptimisticLockError-800]
	_ = x[StatusCacheDataError-801]
	_ = x[StatusTryLockError-802]
}

const (
	_StatusCode_name_0 = "OKUnknown"
	_StatusCode_name_1 = "BadRequestUnauthorizedPaymentRequiredForbiddenNotFoundMethodNotAllowedNotAcceptableProxyAuthRequiredRequestTimeoutConflictGoneLengthRequiredPreconditionFailedRequestEntityTooLargeRequestURITooLongUnsupportedMediaTypeRequestedRangeNotSatisfiableExpectationFailedTeapot"
	_StatusCode_name_2 = "MisdirectedRequestUnprocessableEntityLockedFailedDependencyTooEarlyUpgradeRequired"
	_StatusCode_name_3 = "PreconditionRequiredTooManyRequests"
	_StatusCode_name_4 = "RequestHeaderFieldsTooLarge"
	_StatusCode_name_5 = "UnavailableForLegalReasons"
	_StatusCode_name_6 = "InternalServerError"
	_StatusCode_name_7 = "ServerMaintainJSONUnmarshalError"
	_StatusCode_name_8 = "NotEnoughResourceInstanceNotFoundDuplicatedTransactionAbortRequestCanceled"
	_StatusCode_name_9 = "OptimisticLockErrorCacheDataErrorTryLockError"
)

var (
	_StatusCode_index_0 = [...]uint8{0, 2, 9}
	_StatusCode_index_1 = [...]uint16{0, 10, 22, 37, 46, 54, 70, 83, 100, 114, 122, 126, 140, 158, 179, 196, 216, 244, 261, 267}
	_StatusCode_index_2 = [...]uint8{0, 18, 37, 43, 59, 67, 82}
	_StatusCode_index_3 = [...]uint8{0, 20, 35}
	_StatusCode_index_7 = [...]uint8{0, 14, 32}
	_StatusCode_index_8 = [...]uint8{0, 17, 33, 43, 59, 74}
	_StatusCode_index_9 = [...]uint8{0, 19, 33, 45}
)

func (i StatusCode) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _StatusCode_name_0[_StatusCode_index_0[i]:_StatusCode_index_0[i+1]]
	case 400 <= i && i <= 418:
		i -= 400
		return _StatusCode_name_1[_StatusCode_index_1[i]:_StatusCode_index_1[i+1]]
	case 421 <= i && i <= 426:
		i -= 421
		return _StatusCode_name_2[_StatusCode_index_2[i]:_StatusCode_index_2[i+1]]
	case 428 <= i && i <= 429:
		i -= 428
		return _StatusCode_name_3[_StatusCode_index_3[i]:_StatusCode_index_3[i+1]]
	case i == 431:
		return _StatusCode_name_4
	case i == 451:
		return _StatusCode_name_5
	case i == 500:
		return _StatusCode_name_6
	case 600 <= i && i <= 601:
		i -= 600
		return _StatusCode_name_7[_StatusCode_index_7[i]:_StatusCode_index_7[i+1]]
	case 603 <= i && i <= 607:
		i -= 603
		return _StatusCode_name_8[_StatusCode_index_8[i]:_StatusCode_index_8[i+1]]
	case 800 <= i && i <= 802:
		i -= 800
		return _StatusCode_name_9[_StatusCode_index_9[i]:_StatusCode_index_9[i+1]]
	default:
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
