// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"
	"silo/internal/app/website"
	"silo/internal/config"
	"silo/internal/infra/repo"
	website2 "silo/internal/interface/website"
	"silo/internal/interface/website/handlers"
	"silo/internal/service"
	"silo/pkg/database/dao"
	"silo/pkg/database/db_impl/postgres"
	"silo/pkg/database/db_impl/redis"
	"silo/pkg/platform"
)

// Injectors from wire.go:

func InitApp(cfg *config.CommonConfig, e *echo.Echo) (*website.App, error) {
	postgresConfig := config.ProvidePostgresConfig(cfg)
	db := postgres.NewPostgres(postgresConfig)
	redisConfig := config.ProvideRedisConfig(cfg)
	redisClient := redis.NewRedisClient(redisConfig)
	modelCacheConfig := config.ProvideModelCacheConfig(cfg)
	daoCache := dao.NewDaoCache(db, redisClient, modelCacheConfig)
	exampleRepo := repo.NewExampleRepo(daoCache)
	platformConfig := config.ProvidePlatformConfig(cfg)
	platformClient, err := platform.NewPlatformClient(platformConfig)
	if err != nil {
		return nil, err
	}
	exampleService := service.NewExampleService(exampleRepo, platformClient)
	exampleHandler := handlers.NewExampleHandler(exampleService)
	websiteHandler := website2.NewWebsiteHandler(exampleHandler)
	app := website.NewApp(cfg, e, websiteHandler, db)
	return app, nil
}
