FROM golang:1.24-alpine AS builder
WORKDIR /app
ENV CGO_ENABLED=0
COPY go.mod ./
RUN go mod download
COPY . .
RUN go build -o /out/website ./cmd/website/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /out/website /app/website
WORKDIR /app
ENTRYPOINT ["./website"]
CMD ["start"]