// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mapper

import (
	dto "silo/internal/interface/admin/dto"
	types "silo/internal/service/types"
	search "silo/pkg/database/search"
)

func init() {
	ToTypesExamplePage = func(source *dto.ExamplePageRequest) *types.ExamplePage {
		var pTypesExamplePage *types.ExamplePage
		if source != nil {
			var typesExamplePage types.ExamplePage
			typesExamplePage.Page = searchPageToSearchPage((*source).Page)
			typesExamplePage.Val = (*source).Val
			pTypesExamplePage = &typesExamplePage
		}
		return pTypesExamplePage
	}
}
func searchPageToSearchPage(source search.Page) search.Page {
	var searchPage search.Page
	searchPage.PageIndex = source.PageIndex
	searchPage.PageSize = source.PageSize
	return searchPage
}
