// Code generated by accessor. DO NOT EDIT.
//go:build !accessor

package model

const (
	ExampleColumnId   = "id"
	ExampleColumnInfo = "info"
	ExampleColumnVal  = "val"
)

func (e *Example) SetID(v int64) {
	if e.ID != v {
		e.ID = v
		e.Update(ExampleColumnId, v)
	}
}

func (e *Example) SetInfo(v string) {
	if e.Info != v {
		e.Info = v
		e.Update(ExampleColumnInfo, v)
	}
}

func (e *Example) SetVal(v int64) {
	if e.Val != v {
		e.Val = v
		e.Update(ExampleColumnVal, v)
	}
}
