apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  clusterIP: None
  selector:
    app: admin
  ports:
    - port: 8080
      targetPort: 8080
      name: tcp1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config
      containers:
        - name: admin
          image: silo-admin-server
          imagePullPolicy: Never # TODO Remove this
          args:
            - /app/admin
            - -p
            - "QQFUN"
          envFrom:
            - configMapRef:
                name: server-env
          env:
            - name: QQFUN_APP_SERVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            # Admin服务特定配置覆盖
            - name: QQFUN_APP_NAME
              value: "admin"
            - name: QQFUN_APP_SERVER_PORT
              value: "8080"
            - name: QQFUN_APP_LANGUAGE
              value: "zh-US"
            - name: QQFUN_PLATFORM_ADDR
              value: "http://localhost:8080"
            - name: QQFUN_LOG_FILENAME
              value: "admin.log"
            - name: QQFUN_API_BASE_API_CONFIG_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
          startupProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 20
            exec:
              command:
                - /app/admin
                - -p
                - "QQFUN"
          livenessProbe:
            periodSeconds: 5
            timeoutSeconds: 10
            exec:
              command:
                - /app/admin
                - -p
                - "QQFUN"
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            exec:
              command:
                - /app/admin
                - -p
                - "QQFUN"
      initContainers:
        - name: filebeat
          image: elastic/filebeat:8.16.1
          args:
            - "-e"
            - "--strict.perms=false"
          restartPolicy: Always # makes it as a sidecar container
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml