package main

import (
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/samber/lo"
)

type options struct {
	getter     bool
	setter     bool
	pureGetter bool
	prefix     string
	column     string

	update bool
	method string
	cast   string
}

type optionsFn func(*options)

func WithGetter(v bool) optionsFn {
	return func(o *options) {
		o.getter = v
	}
}

func WithSetter(v bool) optionsFn {
	return func(o *options) {
		o.setter = v
	}
}

func WithPureGetter(v bool) optionsFn {
	return func(o *options) {
		o.pureGetter = v
	}
}

func WithPrefix(p string) optionsFn {
	return func(o *options) {
		o.prefix = p
	}
}

func WithColumn(v string) optionsFn {
	return func(o *options) {
		o.column = v
	}
}

func WithUpdate(v bool) optionsFn {
	return func(o *options) {
		o.update = v
	}
}

func WithCast(v string) optionsFn {
	return func(o *options) {
		o.cast = v
	}
}

func WithMethod(v string) optionsFn {
	return func(o *options) {
		o.method = v
	}
}

func NewGenerator(dir string, pkg string, filename string) *Generator {
	return &Generator{
		Dir:      dir,
		Pkg:      pkg,
		FileName: filename,
		Imports:  []string{},
		Structs:  []Struct{},

		opts: &options{},
	}
}

type Generator struct {
	Dir      string
	Pkg      string
	FileName string
	Imports  []string
	Structs  []Struct

	reflect bool

	opts *options
}

func (g *Generator) InspectImports(unnamedImports []string, namedImports map[string]string) error {
	seenPkgs := make(map[string]struct{})

	for _, s := range g.Structs {
		if pkgName := getPackageNameFromType(s.Type); pkgName != "" {
			if err := g.inspectImport(pkgName, unnamedImports, namedImports, seenPkgs); err != nil {
				return fmt.Errorf("g.inspectImport %s %v %v: %w", pkgName, unnamedImports, namedImports, err)
			}
		}

		for _, field := range s.Fields {
			pkgName := getPackageNameFromType(field.Type)
			if pkgName == "" {
				continue
			}
			if err := g.inspectImport(pkgName, unnamedImports, namedImports, seenPkgs); err != nil {
				return fmt.Errorf("g.inspectImport %s %v %v: %w", pkgName, unnamedImports, namedImports, err)
			}
		}
	}
	return nil
}

func (g *Generator) inspectImport(pkgName string, unnamedImports []string, namedImports map[string]string, seenPkgs map[string]struct{}) error {
	if _, ok := seenPkgs[pkgName]; ok {
		return nil
	}
	seenPkgs[pkgName] = struct{}{}

	if ipt, ok := namedImports[pkgName]; ok {
		g.Imports = append(g.Imports, ipt)
		return nil
	}

	for i, ctn := 0, true; ctn; i++ {
		ctn = false
		for _, ipt := range unnamedImports {
			trimmedIPT := strings.Trim(ipt, "\"")
			names := strings.Split(trimmedIPT, "/")
			p := len(names) - 1 - i
			if p < 0 {
				continue
			}

			ctn = true
			if pkgName == names[p] {
				g.Imports = append(g.Imports, ipt)
				return nil
			}
		}
	}
	return fmt.Errorf("cannot find package %s", pkgName)
}

func (g *Generator) Generate(optsFn ...optionsFn) error {
	g.opts = &options{}
	for _, o := range optsFn {
		o(g.opts)
	}

	// reflect check
	var reflect bool
	for _, s := range g.Structs {
		for _, f := range s.Fields {
			if f.CompareType() == "" {
				reflect = true
			}
		}
	}
	g.reflect = reflect

	cl := g.getPackageCodeLines()
	for _, s := range g.Structs {
		cl = append(cl, g.getStructColumnsLines(s)...)
		cl = append(cl, g.getStructCodeLines(s)...)
	}

	if err := g.writeFile(cl); err != nil {
		return err
	}

	_, err := exec.Command("gofmt", "-w", g.Dir).Output()
	return err
}

func (g *Generator) getPackageCodeLines() (cl lines) {
	cl = cl.Append("// Code generated by %s. DO NOT EDIT.", tagName)
	cl = cl.Append("//go:build !%s", tagName)
	cl = cl.Append("")
	cl = cl.Append("package %s", g.Pkg)

	if g.reflect {
		r := "\"reflect\""
		if !lo.Contains(g.Imports, r) {
			g.Imports = append(g.Imports, r)
		}
	}
	if len(g.Imports) == 1 {
		cl = cl.Append("")
		cl = cl.Append("import %s", g.Imports[0])
		cl = cl.Append("")
	}
	if len(g.Imports) > 1 {
		cl = cl.Append("")
		cl = cl.Append("import (")
		for _, ipt := range g.Imports {
			cl = cl.Append("        %s", ipt)
		}
		cl = cl.Append(")")
		cl = cl.Append("")
	}

	return
}

func (g *Generator) writeFile(cl lines) error {
	var sb strings.Builder
	for _, line := range cl {
		_, err := fmt.Fprintf(&sb, line.format+"\n", line.args...)
		if err != nil {
			return fmt.Errorf("fmt.Fprintf(%s, %v): %w", line.format, line.args, err)
		}
	}

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		return fmt.Errorf("format.Source: %w", err)
	}

	f, err := os.Create(g.filePath())
	if err != nil {
		return fmt.Errorf("os.Create(%s): %w", g.filePath(), err)
	}
	defer f.Close()

	if _, err := f.Write(formatted); err != nil {
		return fmt.Errorf("f.Write: %w", err)
	}
	return nil
}

func (g *Generator) filePath() string {
	return filepath.Join(g.Dir, fmt.Sprintf("%s_%s.go", g.FileName, tagName))
}

func (g *Generator) getPrefix() string {
	if g.opts.pureGetter {
		return ""
	}
	return "get"
}

func (g *Generator) getStructColumnsLines(s Struct) (cl lines) {
	cl = cl.Append("")
	cl = cl.Append("const (")
	for _, field := range s.Fields {
		fieldName := field.Name
		cl = cl.Append("   %s = \"%s\"", ColumnVar(s.Name, g.opts.column, fieldName), field.FieldName(g.opts.cast))
	}
	cl = cl.Append(")")
	return
}

func (g *Generator) getStructCodeLines(s Struct) (cl lines) {
	for _, field := range s.Fields {
		fieldName, fieldType := field.Name, field.Type

		getMethodName := concat(g.getPrefix(), g.opts.prefix, fieldName)
		if g.opts.getter && !s.isNameExist(getMethodName) {
			cl = cl.Append("")
			cl = cl.Append("func (%s *%s) %s() %s {", s.getReceiverName(), s.getReceiverType(), getMethodName, fieldType)
			cl = cl.Append("        return %s.%s", s.getReceiverName(), fieldName)
			cl = cl.Append("}")
		} else if g.opts.getter {
			cl = cl.Append("")
			cl = cl.Append("// %s already exists", getMethodName)
		}

		setMethodName := concat("set", g.opts.prefix, fieldName)
		if g.opts.setter && !s.isNameExist(setMethodName) {
			cl = cl.Append("")
			cl = cl.Append("func (%s *%s) %s(%s %s) {", s.getReceiverName(), s.getReceiverType(), setMethodName, s.newValueName(), fieldType)
			if g.opts.update {
				ct := field.CompareType()
				switch ct {
				case "":
					cl = cl.Append("    if !reflect.DeepEqual(%s.%s, %s) {", s.getReceiverName(), fieldName, s.newValueName())
				case tagOptionEqValue:
					cl = cl.Append("    if %s.%s != %s {", s.getReceiverName(), fieldName, s.newValueName())
				case tagOptionEqForceValue:
					// do nothing
				default:
					cl = cl.Append("    if !%s.%s.%s(%s) {", s.getReceiverName(), fieldName, ct, s.newValueName())
				}

				cl = cl.Append("        %s.%s = %s", s.getReceiverName(), fieldName, s.newValueName())
				cl = cl.Append("        %s.%s(%s, %s)", s.getReceiverName(), g.opts.method, ColumnVar(s.Name, g.opts.column, fieldName), s.newValueName())

				if ct != tagOptionEqForceValue {
					cl = cl.Append("    }")
				}
			} else {
				cl = cl.Append("        %s.%s = %s", s.getReceiverName(), fieldName, s.newValueName())
			}
			cl = cl.Append("}")
		} else if g.opts.setter {
			cl = cl.Append("")
			cl = cl.Append("// %s already exists", setMethodName)
		}
	}
	return
}

type lines []struct {
	format string
	args   []any
}

func (l lines) Append(format string, args ...any) lines {
	return append(l, struct {
		format string
		args   []any
	}{format, args})
}

func NewField(name string, typeStr string, comparable bool, tag Tag) Field {
	return Field{Name: name, Type: typeStr, Comparable: comparable, Tag: tag}
}

type Field struct {
	Name       string
	Type       string
	Comparable bool
	Tag        Tag
}

var typesToUseEqual = []string{"time.Time", "decimal.Decimal", "isotime.ISOTime"}

func (f *Field) CompareType() string {
	if f.Tag.HasOption(tagOptionEqKey) {
		return f.Tag.OptionValue(tagOptionEqKey)
	}

	if lo.Contains(typesToUseEqual, f.Type) {
		return tagOptionEqualMethodValue
	}

	if f.Comparable {
		return tagOptionEqValue
	}

	return ""
}

const CastTypeSnake = "snake"
const CastTypeCamel = "camel"

func ColumnVar(receiverName string, columns string, fieldName string) string {
	return fmt.Sprintf("%s%s%s", receiverName, columns, strcase.ToCamel(fieldName))
}

func (f *Field) FieldName(cast string) string {
	if f.Tag.Name != "" {
		return f.Tag.Name
	}

	switch cast {
	case CastTypeSnake:
		return strcase.ToSnake(f.Name)
	case CastTypeCamel:
		return strcase.ToLowerCamel(f.Name)
	default:
		return f.Name
	}
}

func NewStruct(name string, fields []Field) Struct {
	return Struct{
		Name:   name,
		Type:   name,
		Fields: fields,
	}
}

type Struct struct {
	Name         string
	Type         string
	TypeParams   []string
	ReceiverName string
	Fields       []Field
	Methods      map[string]struct{}
}

func (s Struct) isNameExist(name string) bool {
	if _, ok := s.Methods[name]; ok {
		return true
	}
	for _, field := range s.Fields {
		if field.Name == name {
			return true
		}
	}
	return false
}

func (s *Struct) getReceiverName() string {
	if s.ReceiverName != "" {
		return s.ReceiverName
	}
	s.ReceiverName = strings.ToLower(s.Type[:1])
	return s.ReceiverName
}

func (s *Struct) newValueName() string {
	if s.Name != "v" && s.getReceiverName() != "v" {
		return "v"
	}
	return "val"
}

func (s *Struct) getReceiverType() string {
	if len(s.TypeParams) == 0 {
		return s.Name
	}
	return s.Name + "[" + strings.Join(s.TypeParams, ", ") + "]"
}
