// Code generated by accessor. DO NOT EDIT.
//go:build !accessor

package example

import (
	"accessor/example/other2"
	"reflect"
)

const (
	MyStruct2ColumnOt2 = "ot2"
)

func (m *MyStruct2) SetOT2(v other2.Other2) {
	if !reflect.DeepEqual(m.OT2, v) {
		m.OT2 = v
		m.Update(MyStruct2ColumnOt2, v)
	}
}
