// Code generated by accessor. DO NOT EDIT.
//go:build !accessor

package example

import "time"

const (
	UserModelColumnCreatedAt = "created_at"
	UserModelColumnId        = "_id"
	UserModelColumnStatus    = "st"
	UserModelColumnName      = "name"
)

func (u *UserModel) SetCreatedAt(v time.Time) {
	if !u.CreatedAt.Equal(v) {
		u.CreatedAt = v
		u.Update(UserModelColumnCreatedAt, v)
	}
}

func (u *UserModel) SetID(v int) {
	if u.ID != v {
		u.ID = v
		u.Update(UserModelColumnId, v)
	}
}

func (u *UserModel) SetStatus(v UserStatus) {
	if u.Status != v {
		u.Status = v
		u.Update(UserModelColumnStatus, v)
	}
}

func (u *UserModel) SetName(v string) {
	u.Name = v
	u.Update(UserModelColumnName, v)
}
